ci:
  autofix_commit_msg: "[pre-commit.ci] Fixing issues with pre-commit"
  autofix_prs: true # prs = pull requests
  autoupdate_branch: "master"
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit automatically updated revs."
  autoupdate_schedule: monthly
  skip:
    [clang-tidy, uv-pytest, check-doxygen, check-copyright]
    # we skip clang-tidy because it requires a build directory and llvm installed,
    # but we can't build the C++ package and install llvm with pre-commit.ci
    # so we use GitHub Actions for that instead
  submodules: false # Whether to update submodules during autoupdate

fail_fast: true # Stop running other hooks even if one fails

repos:
  # UV: Python package and project manager
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.1
    hooks:
      - id: uv-lock # To make sure the uv.lock file is up to date with the pyproject.toml file
      - id: uv-export # To keep a requirements.txt file in sync with the uv.lock file
        args: ["--output-file=requirements.txt", "--quiet", "--all-groups"]

  # Codespell: Spell checker
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        args:
          - --skip=*.js,*.html,*.css,*.pdf,*.png,*.csv,*.pkl,*.json,*.xml
          - --ignore-words-list=teh,fo,bar,tesselator,Tesselator,tesselation,tesselate
        files: '\.(py|md|c|cpp|h|hpp|rst|sh)$'

  # Ruff: Linter and Formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff
        args: ["--fix"]
        types_or: ["python", "pyi"]
      # Formatting with Ruff
      - id: ruff-format
        types_or: ["python", "pyi"]

  # Mypy: Static type checker for python files
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.0
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies:
          - numpy
          - pytest

  # Numpydoc Validation: Ensure docstring compliance
  - repo: https://github.com/numpy/numpydoc
    rev: v1.11.0rc0
    hooks:
      - id: numpydoc-validation
        files: ^(src|tests)/.*\.py$

  # nbQA: formatting and linting for Jupyter notebooks
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        args: ["--extend-ignore=D100,E402"]
        additional_dependencies: [ruff, jupytext]

      - id: nbqa-pyupgrade
        args: ["--py37-plus"]
        additional_dependencies: [pyupgrade, jupytext]

  # Check if the copyright header is present and correct on all source files .cpp, .h and .py
  - repo: local
    hooks:
      - id: check-copyright
        name: check-copyright
        entry: ./.check-copyright.sh
        language: system
        pass_filenames: false
        always_run: true

  # shfmt: Formatter for shell scripts
  - repo: https://github.com/maxwinterstein/shfmt-py
    rev: v4.0.0
    hooks:
      - id: shfmt
        args:
          - -i
          - "2"
          - -ci
        files: \.(sh|bash|zsh)$

  # Cppcheck: C++ static analysis
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.8
    hooks:
      - id: clang-format
        args: [--style=file]
        files: \.(cpp|h|hpp|c)$

  # Cppcheck: C++ static analysis
  - repo: https://github.com/pocc/pre-commit-hooks # requires llvm installed
    rev: v1.3.5
    hooks:
      - id: clang-tidy # The user need to have build the C++ project with CMake first
        args: [-p=src/mechanical_layer/build]

  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.2
    hooks:
      - id: cpplint
        args: [--filter=-runtime/string]
        exclude: src/mechanical_layer/3rdparty/tinyxml/tinyxml2\.(h|cpp)$

  # Doxygen: Documentation generator
  - repo: local
    hooks:
      - id: check-doxygen
        name: check-doxygen
        entry: ./.check-doxygen.sh
        files: \.(h|hpp|cpp|c)$
        language: system
        pass_filenames: false

  # Test of python functions
  - repo: local
    hooks:
      - id: uv-pytest
        name: pytest
        entry: uv run pytest -n auto tests/configuration
        language: system
        pass_filenames: false
        always_run: true
        types: ["python"]
