[project]
name = "shape-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cmcrameri>=1.9",
    "dicttoxml>=1.7.16",
    "kaleido==0.2.1",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "pyvista>=0.44.1",
    "ruff>=0.9.9",
    "scipy>=1.15.2",
    "shapely>=2.0.7",
    "streamlit>=1.43.0",
    "streamlit-option-menu>=0.4.0",
    "watchdog>=6.0.0",
]
