[project]
name = "shape-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cmcrameri>=1.9",
    "dicttoxml>=1.7.16",
    "kaleido==0.2.1",
    "matplotlib>=3.10.1",
    "mypy>=1.15.0",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "pyvista>=0.44.1",
    "scipy>=1.15.2",
    "shapely>=2.0.7",
    "streamlit>=1.43.0",
    "streamlit-option-menu>=0.4.0",
    "watchdog>=6.0.0",
]

[project.optional-dependencies]
dev = [
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
    "mypy>=1.15.0",            # Static type checker
    "ruff>=0.9.9",             # Linter and formatter
    "pre-commit>=4.1.0",       # Pre-commit framework
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
